color0 #424659
color1 #ffb4ab
color2 #5ed4fc
color3 #88d0ec
color4 #b6c4ff
color5 #5ed4fc
color6 #88d0ec
color7 #e1e1ef
color8 #8c90a6
color9 #ffb4ab
color10 #5ed4fc
color11 #88d0ec
color12 #b6c4ff
color13 #5ed4fc
color14 #88d0ec
color15 #e1e1ef

cursor                #e1e1ef
cursor_text_color     #11131c
background            #11131c
foreground            #e1e1ef
selection_foreground  #c2c5dd
selection_background  #424659
active_border_color   #5ed4fc
inactive_border_color #424659
url_color             #5ed4fc

active_tab_foreground   #003544
active_tab_background   #5ed4fc
inactive_tab_foreground #c2c5dd
inactive_tab_background #424659
cursor_trail_color      #c2c5dd
