color0 #404659
color1 #ffb4ab
color2 #56d6f5
color3 #85d2e8
color4 #afc6ff
color5 #56d6f5
color6 #85d2e8
color7 #e0e2ef
color8 #8a90a5
color9 #ffb4ab
color10 #56d6f5
color11 #85d2e8
color12 #afc6ff
color13 #56d6f5
color14 #85d2e8
color15 #e0e2ef

cursor                #e0e2ef
cursor_text_color     #10131c
background            #10131c
foreground            #e0e2ef
selection_foreground  #bfc6dc
selection_background  #404659
active_border_color   #56d6f5
inactive_border_color #404659
url_color             #56d6f5

active_tab_foreground   #003641
active_tab_background   #56d6f5
inactive_tab_foreground #bfc6dc
inactive_tab_background #404659
cursor_trail_color      #bfc6dc
