color0 #0d4431
color1 #fd4663
color2 #67e4b8
color3 #54c9de
color4 #74cc66
color5 #93eccc
color6 #94ddea
color7 #f2f3f2
color8 #647a72
color9 #fd4663
color10 #67e4b8
color11 #54c9de
color12 #74cc66
color13 #93eccc
color14 #94ddea
color15 #f2f3f2

cursor                #f2f3f2
cursor_text_color     #0a3325
background            #0a3325
foreground            #f2f3f2
selection_foreground  #afb6b4
selection_background  #0d4431
active_border_color   #67e4b8
inactive_border_color #0d4431
url_color             #67e4b8

active_tab_foreground   #182520
active_tab_background   #67e4b8
inactive_tab_foreground #afb6b4
inactive_tab_background #0d4431
cursor_trail_color      #afb6b4
