color0 #48464c
color1 #ffb4ab
color2 #c9c3dc
color3 #c9c5cf
color4 #debecd
color5 #c9c3dc
color6 #c9c5cf
color7 #e5e1e3
color8 #928f97
color9 #ffb4ab
color10 #c9c3dc
color11 #c9c5cf
color12 #debecd
color13 #c9c3dc
color14 #c9c5cf
color15 #e5e1e3

cursor                #e5e1e3
cursor_text_color     #141315
background            #141315
foreground            #e5e1e3
selection_foreground  #c9c5cd
selection_background  #48464c
active_border_color   #c9c3dc
inactive_border_color #48464c
url_color             #c9c3dc

active_tab_foreground   #312e41
active_tab_background   #c9c3dc
inactive_tab_foreground #c9c5cd
inactive_tab_background #48464c
cursor_trail_color      #c9c5cd
