# source = ~/.config/colors/hyprColorsGen.conf

# General-Appearance
general {
    # --- Gaps & Borders ---
    gaps_in = 4                 # Gap between windows
    gaps_out = 4              # Gap between windows and monitor edges
    gaps_workspaces = 0         # Gap between workspaces (when sliding)
    border_size = 2             # Size of window borders

    col.active_border = rgb(ffffff)
    col.inactive_border = rgb(000000)

    resize_on_border = false

    allow_tearing = true

    layout = dwindle

    snap {
        enabled = false
        window_gap = 10         # Min gap (px) before snapping to another window
        monitor_gap = 10        # Min gap (px) before snapping to monitor edge
        border_overlap = false  # If true, windows snap with overlapping borders
    }
}

#  Decorations
decoration {
    #  Rounding 
    rounding = 10
    rounding_power = 6.0

    #  Opacity 
    active_opacity = 1.0
    inactive_opacity = 0.8
    fullscreen_opacity = 1.0

    #  Dimming 
    dim_inactive = false
    dim_strength = 0.2
    dim_special = 0.8           # Stronger dimming for special workspace

    #  Shadows 
    shadow {
        enabled = false
        range = 35
        render_power = 2        # 1-4. Higher is faster falloff (sharper looking)
        sharp = false           # If true, renders a sharp shadow (retro style)
        # ignore_window = true    # If true, shadow isn't rendered behind the window itself
        scale = 1.0             # Scale of the shadow (1.0 = window size)
        color = rgba(1a1a1aee)
    }

    #  Blur 
    blur {
        enabled = true
        size = 3                # Radius
        passes = 3             # Quality (2 is a good balance of perf/looks)
        new_optimizations = true
        ignore_opacity = true   # Blurs behind transparent windows even if opacity is high
        xray = false            # If true, floating windows "see through" tiled ones
		vibrancy = 0.5 
        noise = 0.0117          # Adds grain to prevent color banding
        contrast = 0.8916       # Contrast modulation for blur
        brightness = 0.8172     # Brightness modulation for blur
        vibrancy = 0.1696       # Saturation of blurred colors
        
        popups = true      # Whether to blur right-click menus/popups
    }
}

# Animations

source = ~/.config/hypr/source/animations/vertical_dusky.conf

# Layouts
dwindle {
    # pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

# Others
misc {
    force_default_wallpaper = 1     # Set to 0 to enable the anime mascot
    disable_hyprland_logo = true
    disable_splash_rendering = true
}

