env = XDG_CURRENT_DESKTOP,Hyprland

# Qt-Environment-Variables
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_QPA_PLATFORMTHEME,qt5ct

# Cursor-Theme
env = XCURSOR_THEME, macOS-White
env = XCURSOR_SIZE, 24

evn = GTK_THEME, adw-gtk3

