xwayland {
    force_zero_scaling = true
}

# termfilechooser
windowrule {
  name=termfilechooser
  float = true
  center = true
  size =  900 600
  match:title = ^(termfilechooser)$
}

# yazi
windowrule {
  name=yazi
  float = true
  center = true
  size =  900 600
  match:class = ^(yazi)$
}

# noctalia-settings
windowrule {
  name=noctalia-settings
  float = true
  center = true
  size =  1000 700
  match:class = ^(dev.noctalia.Noctalia.Settings)$
}

