xwayland {
    force_zero_scaling = true
}

# termfilechooser
windowrule {
  name=termfilechooser
  float = true
  center = true
  size =  900 600
  match:title = ^(termfilechooser)$
}

# yazi
windowrule {
  name=yazi
  float = true
  center = true
  size =  900 600
  match:class = ^(yazi)$
}

# awtwall
windowrule {
  name=awtwall
  float = true
  center = true
  size =  950 600
  match:class = ^(awtwall)$
}
