source = ~/.config/hypr/source/monitors.conf
source = ~/.config/hypr/source/permissions.conf
source = ~/.config/hypr/source/plugins.conf
source = ~/.config/hypr/source/input.conf
source = ~/.config/hypr/source/appearance.conf
source = ~/.config/hypr/source/windowRules.conf
source = ~/.config/hypr/source/layerRules.conf
source = ~/.config/hypr/source/keybinds.conf
source = ~/.config/hypr/source/autostart.conf
source = ~/.config/hypr/source/environmentVariables.conf
source = ~/.config/hypr/source/workspaceRules.conf




# For Noctalia Color templates
source = ~/.config/hypr/noctalia.conf
