$primary = rgb(67e4b8)
$surface = rgb(0a3325)
$secondary = rgb(54c9de)
$error = rgb(fd4663)
$tertiary = rgb(74cc66)
$surface_lowest = rgb(051a12)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
